# Change these first
owner: txyyddss # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository
sites:
  - name: TX Service Index
    url: https://1919801.xyz
  - name: Webmap(CF+IPV6)
    url: https://map.1919801.xyz/maps/world/live/players.json
  - name: Webmap(ZT)
    url: http://114.114.51.4:8123/maps/world/live/players.json
  - name: Game Server(ZT)
    check: "tcp-ping"
    url: 114.114.51.4
    port: 11451
  - name: IPV4(MT)
    url: https://proxyv6mc.1919801.xyz/mt
  - name: IPV4(TX)
    url: https://proxymy.1919801.xyz
  - name: Service Status
    url: https://s.1919801.xyz
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.1919801.xyz
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/txyyddss/upptime/master/static/img/icon.svg
  name: TX Status Page
  introTitle: "A status page powered entirely by GitHub and Cloudflare."
  introMessage: Welcome, also see [TX Index](https://1919801.xyz/).
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
